<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WordStation.DAL\WordStation.DAL.csproj" />
    <ProjectReference Include="..\WordStation.EL\WordStation.EL.csproj" />
  </ItemGroup>

</Project>
