name: Deploy WebAPI

run-name: Deploy WebAPI - ${{ github.event.head_commit.message }} - ${{ github.sha }}

on:
  push:
    branches: [ main ]
    paths:
      - 'WordStation.WebAPI/**'
      - 'WordStation.BLL/**'
      - 'WordStation.DAL/**'
      - 'WordStation.EL/**'
      - '.github/workflows/deploy-webapi.yml'
  workflow_dispatch:

concurrency:
  group: deploy-webapi
  cancel-in-progress: true

jobs:
  build-and-deploy-api:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore WordStation.sln

    - name: Run Tests
      run: dotnet test WordStation.Tests --no-restore -c Release

    - name: Build
      run: dotnet build WordStation.WebAPI -c Release --no-restore

    - name: Deploy API with Web Deploy
      run: |
        dotnet publish WordStation.WebAPI -c Release `
          /p:WebPublishMethod=MSDeploy `
          /p:MSDeployPublishMethod=WMSVC `
          /p:MsDeployServiceUrl=${{ secrets.WEBAPI_SERVER }} `
          /p:DeployIisAppPath=${{ secrets.WEBAPI_SITENAME }} `
          /p:UserName=${{ secrets.WEBAPI_USERNAME }} `
          /p:Password=${{ secrets.WEBAPI_PASSWORD }} `
          /p:AllowUntrustedCertificate=true `
          /p:EnableMsDeployAppOffline=true `
          /p:SkipExtraFilesOnServer=true
