name: WebAPI-CD

on:
  workflow_run:
    workflows: ["WebAPI-CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploy WebAPI
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Update Production secrets
      shell: pwsh
      env:
        SQL_CONN_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
        JWT_SECRET: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        $appsettingsPath = "WordStation.WebAPI/appsettings.Production.json"
        $json = Get-Content $appsettingsPath -Raw | ConvertFrom-Json
        $json.ConnectionStrings.sqlConnection = $env:SQL_CONN_STRING
        $json.JwtSettings.SecretKey = $env:JWT_SECRET
        $json | ConvertTo-Json -Depth 10 | Set-Content $appsettingsPath
    - name: Deploy API
      run: |
        dotnet publish WordStation.WebAPI -c Release `
          /p:WebPublishMethod=MSDeploy `
          /p:MSDeployPublishMethod=WMSVC `
          /p:MsDeployServiceUrl=${{ secrets.WEBAPI_SERVER }} `
          /p:DeployIisAppPath=${{ secrets.WEBAPI_SITENAME }} `
          /p:UserName=${{ secrets.WEBAPI_USERNAME }} `
          /p:Password=${{ secrets.WEBAPI_PASSWORD }} `
          /p:AllowUntrustedCertificate=true `
          /p:EnableMsDeployAppOffline=true `
          /p:SkipExtraFilesOnServer=true
