name: WebAPI-CD

on:
  workflow_dispatch: # GitHub UI üzerinden manuel olarak tetiklemeyi sağlar
  workflow_run:
    workflows: ["WebAPI-CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploy WebAPI
    runs-on: windows-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Create appsettings.json from Secrets
      shell: pwsh
      run: |
        $appsettings = @"
        ${{ secrets.API_APPSETTINGS_JSON }}
        "@
        $appsettings | Out-File -FilePath "WordStation.WebAPI/appsettings.json" -Encoding utf8
    - name: Deploy API
      run: |
        dotnet publish WordStation.WebAPI -c Release `
          /p:WebPublishMethod=MSDeploy `
          /p:MSDeployPublishMethod=WMSVC `
          /p:MsDeployServiceUrl=${{ secrets.WEBAPI_SERVER }} `
          /p:DeployIisAppPath=${{ secrets.WEBAPI_SITENAME }} `
          /p:UserName=${{ secrets.WEBAPI_USERNAME }} `
          /p:Password=${{ secrets.WEBAPI_PASSWORD }} `
          /p:AllowUntrustedCertificate=true `
          /p:EnableMsDeployAppOffline=true `
          /p:SkipExtraFilesOnServer=true
