name: WebUI-CD

on:
  workflow_dispatch: # GitHub UI üzerinden manuel olarak tetiklemeyi sağlar
  workflow_run:
    workflows: ["WebUI-CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploy WebUI
    runs-on: windows-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Create appsettings.json from Secrets
      shell: pwsh
      env:
        APPSETTINGS_JSON: ${{ secrets.WEBUI_APPSETTINGS_JSON }}
      run: |
        $env:APPSETTINGS_JSON | Out-File -FilePath "WordStation.WebUI/appsettings.json" -Encoding utf8
    - name: Deploy WebUI
      shell: pwsh
      env:
        WEB_DEPLOY_JSON: ${{ secrets.WEB_DEPLOY_JSON }}
      run: |
        $deployConfig = $env:WEB_DEPLOY_JSON | ConvertFrom-Json
        $server = $deployConfig.WebUI.Server
        if (-not $server.StartsWith("http")) {
            $server = "https://$server/MsDeploy.axd"
        }
        $site = $deployConfig.WebUI.SiteName
        $user = $deployConfig.WebUI.UserName
        $pass = $deployConfig.WebUI.Password

        dotnet publish WordStation.WebUI -c Release `
          /p:WebPublishMethod=MSDeploy `
          /p:MSDeployPublishMethod=WMSVC `
          /p:MsDeployServiceUrl="$server" `
          /p:DeployIisAppPath="$site" `
          /p:UserName="$user" `
          /p:Password="$pass" `
          /p:AllowUntrustedCertificate=true `
          /p:EnableMsDeployAppOffline=true `
          /p:SkipExtraFilesOnServer=true
